dist: trusty

language: python

python:
    - '2.7'
    - '3.4'

before_install:
  - pip install pytest pytest-cov

install:
  - pip install .
  - cd && find -name gitfaces

script:
  - cd test && GITFACES_REPO=$HOME/build/nschloe/gitfaces pytest --cov gitfaces

after_success:
  - bash <(curl -s https://codecov.io/bash)
