#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
import argparse

# pylint: disable=import-self
import gitfaces


def _parse_cmd_arguments():
    parser = argparse.ArgumentParser(
        description='fetch contributor avatars for a GitHub repository'
        )
    parser.add_argument(
        'repo',
        type=str,
        help='local Git repository'
        )
    parser.add_argument(
        'outdir',
        type=str,
        help='output directory'
        )
    return parser.parse_args()


if __name__ == '__main__':
    args = _parse_cmd_arguments()
    gitfaces.fetch(args.repo, args.outdir)
